=== ds-horizon/odin-component-interface/src/test/groovy/aerospike/container/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "imageRegistry": {
      "type": "string"
    },
    "imageRepository": {
      "type": "string"
    },
    "imageTag": {
      "type": "string"
    },
    "storageClass": {
      "type": "string"
    },
    "nodeSelector": {
      "type": "string"
    },
    "replicaCount": {
      "type": "integer"
    },
    "resources": {
      "type": "object",
      "properties": {
        "limits": {
          "type": "object",
          "properties": {
            "cpu": {
              "type": "string"
            },
            "memory": {
              "type": "string"
            },
            "ephemeralStorage": {
              "type": "string"
            }
          },
          "required": [
            "cpu",
            "memory",
            "ephemeralStorage"
          ]
        },
        "requests": {
          "type": "object",
          "properties": {
            "cpu": {
              "type": "string"
            },
            "memory": {
              "type": "string"
            },
            "ephemeralStorage": {
              "type": "string"
            }
          },
          "required": [
            "cpu",
            "memory",
            "ephemeralStorage"
          ]
        }
      },
      "required": [
        "limits",
        "requests"
      ]
    }
  },
  "required": [
    "imageRegistry",
    "imageRepository",
    "imageTag",
    "storageClass",
    "nodeSelector",
    "replicaCount",
    "resources"
  ]
}

=== ds-horizon/odin-component-interface/src/test/groovy/aerospike/container/defaults.json
{
  "imageRegistry": "dreamsports.jfrog.io",
  "imageRepository": "d11-docker-artifacts/aerospike",
  "imageTag": "4.3.0.8",
  "storageClass": "gp2",
  "nodeSelector": "ON_DEMAND",
  "replicaCount": 1,
  "resources": {
    "limits": {
      "cpu": "1000m",
      "memory": "4000Mi",
      "ephemeralStorage": "2Gi"
    },
    "requests": {
      "cpu": "500m",
      "memory": "3000Mi",
      "ephemeralStorage": "1Gi"
    }
  }
}
